# Generated by Django 2.2.8 on 2019-12-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddaj_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Fundacja', 'Fundacja'), ('Organizacja', 'Organizacja pozarządowa'), ('Zbiorka', 'Zbiórka lokalna')], default='Fundacja', max_length=124)),
                ('categories', models.ManyToManyField(to='oddaj_app.Category')),
            ],
        ),
    ]
